"""create incidents table

Revision ID: c8c2ee2bebaa
Revises: 
Create Date: 2026-07-24 23:48:39.937540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8c2ee2bebaa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('failure_duration_minutes', sa.Float(), nullable=False),
    sa.Column('reconstructed', sa.Boolean(), nullable=False),
    sa.Column('observability', sa.Float(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('active_failures', sa.Integer(), nullable=False),
    sa.Column('reconstructed_nodes', sa.Integer(), nullable=False),
    sa.Column('network_status', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_index('ix_incidents_event_type', 'incidents', ['event_type'], unique=False)
    op.create_index('ix_incidents_sensor_id', 'incidents', ['sensor_id'], unique=False, postgresql_where=sa.text('sensor_id IS NOT NULL'))
    op.create_index('ix_incidents_timestamp', 'incidents', [sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_timestamp', table_name='incidents')
    op.drop_index('ix_incidents_sensor_id', table_name='incidents', postgresql_where=sa.text('sensor_id IS NOT NULL'))
    op.drop_index('ix_incidents_event_type', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
