import httpx
from typing import Dict, Any, List

API_BASE_URL = "http://localhost:8000"

def _fetch_state() -> Dict[str, Any]:
    """Helper to fetch the current system state from the backend."""
    try:
        response = httpx.get(f"{API_BASE_URL}/state", timeout=5.0)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        return {"error": f"Failed to fetch state from backend: {e}"}

def _calculate_observability(state_data: Dict[str, Any]) -> float:
    """Helper to calculate observability percentage."""
    snapshot = state_data.get("snapshot", {})
    masks = snapshot.get("masks", {})
    reconstructions = snapshot.get("reconstructions", {})
    
    num_nodes = len(masks)
    if num_nodes == 0:
        return 100.0
        
    active_failures = sum(1 for v in masks.values() if v)
    reconstructed_nodes = len(reconstructions)
    
    return ((num_nodes - active_failures + reconstructed_nodes) / num_nodes) * 100.0

def get_network_health() -> Dict[str, Any]:
    """
    Returns the overall network status, observability percentage, and the count of active failures.
    """
    state_data = _fetch_state()
    if "error" in state_data:
        return state_data
        
    snapshot = state_data.get("snapshot", {})
    active_failures = sum(1 for v in snapshot.get("masks", {}).values() if v)
    observability = _calculate_observability(state_data)
    
    return {
        "network_status": state_data.get("system_health", "unknown"),
        "observability_percent": round(observability, 2),
        "active_failures_count": active_failures
    }

def get_active_failures() -> Dict[str, Any]:
    """
    Returns a list of currently failed sensor IDs in the network.
    """
    state_data = _fetch_state()
    if "error" in state_data:
        return state_data
        
    masks = state_data.get("snapshot", {}).get("masks", {})
    failed_sensors = [sensor_id for sensor_id, is_failed in masks.items() if is_failed]
    
    return {
        "failed_sensors": failed_sensors,
        "total_failed": len(failed_sensors)
    }

def get_latest_incidents() -> Dict[str, Any]:
    """
    Returns the latest incident summaries generated by the incident intelligence service.
    """
    try:
        response = httpx.get(f"{API_BASE_URL}/incident-summaries", timeout=5.0)
        response.raise_for_status()
        incidents = response.json()
        return {"latest_incidents": incidents}
    except Exception as e:
        return {"error": f"Failed to fetch incident summaries: {e}"}

def get_system_metrics() -> Dict[str, Any]:
    """
    Returns system performance metrics including MAE, RMSE, FCR, and current observability.
    """
    state_data = _fetch_state()
    if "error" in state_data:
        return state_data
        
    metrics = state_data.get("metrics", {})
    observability = _calculate_observability(state_data)
    
    return {
        "mae": round(metrics.get("mae", 0.0), 4),
        "rmse": round(metrics.get("rmse", 0.0), 4),
        "fcr": round(metrics.get("fcr", 0.0), 2),
        "observability_percent": round(observability, 2)
    }

def get_sensor_status(sensor_id: str) -> Dict[str, Any]:
    """
    Returns the detailed status for a specific sensor, including its current state, 
    live speed reading, and whether it has been reconstructed.
    
    Args:
        sensor_id: The ID of the sensor as a string (e.g., "0", "42").
    """
    state_data = _fetch_state()
    if "error" in state_data:
        return state_data
        
    snapshot = state_data.get("snapshot", {})
    masks = snapshot.get("masks", {})
    readings = snapshot.get("readings", {})
    reconstructions = snapshot.get("reconstructions", {})
    
    sensor_id_str = str(sensor_id)
    
    if sensor_id_str not in masks:
        return {"error": f"Sensor ID {sensor_id_str} not found in network."}
        
    is_failed = masks.get(sensor_id_str, False)
    is_reconstructed = sensor_id_str in reconstructions
    
    status = "offline" if is_failed else "online"
    
    speed = None
    if is_reconstructed:
        speed = reconstructions.get(sensor_id_str)
    elif not is_failed:
        speed = readings.get(sensor_id_str)
        
    return {
        "sensor_id": sensor_id_str,
        "status": status,
        "is_reconstructed": is_reconstructed,
        "current_speed": speed
    }
